/*
 * spi.h
 *
 *  Created on: 19.11.2020
 *      Author: mariusz
 */

#ifndef SPI_SPI1_H_
#define SPI_SPI1_H_

#include "common.h"

#define SPI1_SCK_GPIOA_EN	RCC->AHBENR |= RCC_AHBENR_GPIOAEN
#define SPI1_SCK_GPIOB_EN	RCC->AHBENR |= RCC_AHBENR_GPIOBEN
#define SPI1_SCK_GPIOA_AF	GPIO_AF0
#define SPI1_SCK_GPIOB_AF	GPIO_AF0
#define SPI1_SCK_GPIOA		GPIOA
#define SPI1_SCK_GPIOB		GPIOB
#define SPI1_SCK_PA5		PA5
#define SPI1_SCK_PB3		PB3

#define SPI1_MISO_GPIOA_EN	RCC->AHBENR |= RCC_AHBENR_GPIOAEN
#define SPI1_MISO_GPIOB_EN	RCC->AHBENR |= RCC_AHBENR_GPIOBEN
#define SPI1_MISO_GPIOA_AF	GPIO_AF0
#define SPI1_MISO_GPIOB_AF	GPIO_AF0
#define SPI1_MISO_GPIOA		GPIOA
#define SPI1_MISO_GPIOB		GPIOB
#define SPI1_MISO_PA5		PA6
#define SPI1_MISO_PB4		PB4

#define SPI1_MOSI_GPIOA_EN	RCC->AHBENR |= RCC_AHBENR_GPIOAEN
#define SPI1_MOSI_GPIOB_EN	RCC->AHBENR |= RCC_AHBENR_GPIOBEN
#define SPI1_MOSI_GPIOA_AF	GPIO_AF0
#define SPI1_MOSI_GPIOB_AF	GPIO_AF0
#define SPI1_MOSI_GPIOA		GPIOA
#define SPI1_MOSI_GPIOB		GPIOB
#define SPI1_MOSI_PA7		PA7
#define SPI1_MOSI_PB5		PB5

#define SPI1_CPOL_LOW		0x00
#define SPI1_CPOL_HIGH		0x01

#define SPI1_CPHA_FIRST		0x00
#define SPI1_CPHA_SECOND	0x01

#define SPI1_FPCLK2			0x00
#define SPI1_FPCLK4			0x01
#define SPI1_FPCLK8			0x02
#define SPI1_FPCLK16		0x03
#define SPI1_FPCLK32		0x04
#define SPI1_FPCLK64		0x05
#define SPI1_FPCLK128		0x06
#define SPI1_FPCLK256		0x07

#define SPI1_MSB_FIRST		0x00
#define SPI1_LSB_FIRST		0x00

#define SPI1_MODE_HALF_DUPLEX_MASTER	0x00
#define SPI1_MODE_FULL_DUPLEX_MASTER	0x01

// User Configuartion
#define SPI1_SCK_PORT_EN	SPI1_SCK_GPIOA_EN
#define SPI1_SCK_PORT		SPI1_SCK_GPIOA
#define SPI1_SCK_AF			SPI1_SCK_GPIOA_AF
#define SPI1_SCK_PIN		SPI1_SCK_PA5

#define SPI1_MISO_PORT_EN	SPI1_MISO_GPIOB_EN
#define SPI1_MISO_PORT		SPI1_MISO_GPIOB
#define SPI1_MISO_AF		SPI1_MISO_GPIOB_AF
#define SPI1_MISO_PIN		SPI1_MISO_PB4

#define SPI1_MOSI_PORT_EN	SPI1_MOSI_GPIOA_EN
#define SPI1_MOSI_PORT		SPI1_MOSI_GPIOA
#define SPI1_MOSI_AF		SPI1_MOSI_GPIOA_AF
#define SPI1_MOSI_PIN		SPI1_MOSI_PA7

#define SPI1_CPOL			SPI1_CPOL_LOW
#define SPI1_CPHA			SPI1_CPHA_FIRST
#define SPI1_FPCLK			SPI1_FPCLK8
#define SPI1_FORMAT			SPI1_MSB_FIRST

#define SPI1_MODE			SPI1_MODE_HALF_DUPLEX_MASTER
// User Configuartion End

void spi1_set(void);
uint8_t spi1_transfer(uint8_t data);

#endif /* SPI_SPI1_H_ */
